name: componentes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/img1.jpg
    - assets/img/img2.jpg
    - assets/img/img3.jpg
    - assets/img/img4.jpg
    - assets/img/img5.jpg